// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_DVHC
    {
        [Key]
        public int IDx { get; set; }
        [Required]
        [StringLength(150)]
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string TenTiengAnh { get; set; }
        [StringLength(150)]
        public string Cap { get; set; }
        public int? Loai { get; set; }
        [StringLength(150)]
        public string MaQuanHuyen { get; set; }
        public string TenQuanHuyen { get; set; }
        [StringLength(150)]
        public string MaTinhTP { get; set; }
        public string TenTinhThanhPho { get; set; }
        public int? ID_Map_HIS { get; set; }
    }
}