// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_ICD
    {
        public DM_ICD()
        {
            DM_ICD_Common = new HashSet<DM_ICD_Common>();
            K_KhamBenh = new HashSet<K_KhamBenh>();
        }

        [Key]
        public int ICD_Id { get; set; }
        [StringLength(20)]

        public string MaICD { get; set; }
        [StringLength(200)]
        public string TenICD { get; set; }
        [StringLength(200)]
        public string TenICD_En { get; set; }
        [StringLength(200)]
        public string TenICD_Ru { get; set; }
        [StringLength(3)]

        public string MucICD { get; set; }
        public int? ICD_Nhom_Id { get; set; }
        [StringLength(7)]

        public string PhanNhom { get; set; }
        public short? Loai { get; set; }
        public bool BenhTruyenNhiem { get; set; }
        public bool? TamNgung { get; set; }
        [StringLength(200)]
        public string TenKhongDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public int? Ma { get; set; }

        [ForeignKey("ICD_Nhom_Id")]
        [InverseProperty("DM_ICD")]
        public virtual DM_ICD_Nhom ICD_Nhom { get; set; }
        [InverseProperty("ICD")]
        public virtual ICollection<DM_ICD_Common> DM_ICD_Common { get; set; }
        [InverseProperty("ICD")]
        public virtual ICollection<K_KhamBenh> K_KhamBenh { get; set; }
    }
}