// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_ICD_Chuong
    {
        public DM_ICD_Chuong()
        {
            DM_ICD_Nhom = new HashSet<DM_ICD_Nhom>();
        }

        [Key]
        public int ICD_Chuong_Id { get; set; }
        [StringLength(20)]

        public string MaChuongICD { get; set; }
        [StringLength(200)]
        public string TenChuongICD { get; set; }
        [StringLength(200)]
        public string TenChuongICD_En { get; set; }
        [StringLength(200)]
        public string TenChuongICD_Ru { get; set; }
        public bool TamNgung { get; set; }
        [StringLength(200)]
        public string TenKhongDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }

        [InverseProperty("ICD_Chuong")]
        public virtual ICollection<DM_ICD_Nhom> DM_ICD_Nhom { get; set; }
    }
}