// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_ICD_Nhom
    {
        public DM_ICD_Nhom()
        {
            DM_ICD = new HashSet<DM_ICD>();
        }

        [Key]
        public int ICD_Nhom_Id { get; set; }
        [StringLength(20)]

        public string MaNhomICD { get; set; }
        [StringLength(200)]
        public string TenNhomICD { get; set; }
        [StringLength(200)]
        public string TenNhomICD_En { get; set; }
        [StringLength(200)]
        public string TenNhomICD_Ru { get; set; }
        public int? ICD_Chuong_Id { get; set; }
        public bool TamNgung { get; set; }
        [StringLength(200)]
        public string TenKhongDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }

        [ForeignKey("ICD_Chuong_Id")]
        [InverseProperty("DM_ICD_Nhom")]
        public virtual DM_ICD_Chuong ICD_Chuong { get; set; }
        [InverseProperty("ICD_Nhom")]
        public virtual ICollection<DM_ICD> DM_ICD { get; set; }
    }
}