// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_ICD_Common
    {
        [Key]
        public int ICD_Common_Id { get; set; }
        public int BacSi_Id { get; set; }
        public int ICD_Id { get; set; }

        [ForeignKey("BacSi_Id")]
        [InverseProperty("DM_ICD_Common")]
        public virtual K_BacSi BacSi { get; set; }
        [ForeignKey("ICD_Id")]
        [InverseProperty("DM_ICD_Common")]
        public virtual DM_ICD ICD { get; set; }
    }
}