// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class DM_LoaiKho
    {
        [Key]
        public int LoaiKho_ID { get; set; }
        [Column("DM_LoaiKho")]
        [StringLength(100)]
        public string DM_LoaiKho1 { get; set; }
        [StringLength(100)]
        public string TenKho { get; set; }
    }
}