// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    [Table("DM_LoaiGia", Schema = "db_accessadmin")]
    public partial class DM_LoaiGia
    {
        [Key]
        public int LoaiGia_ID { get; set; }
        [StringLength(100)]
        public string TenLoaiGia { get; set; }
    }
}