// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    [Table("itemSelect")]
    public partial class ItemSelect
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]

        public string ValueItemString { get; set; }
        public int? ValueItemInt { get; set; }
        [StringLength(100)]
        public string ShowText { get; set; }
        public int? NumericalOrder { get; set; }
        [Column(TypeName = "ntext")]
        public string QueryDatabase { get; set; }
        [StringLength(100)]
        public string ColumnKey { get; set; }
        [StringLength(100)]
        public string ColumnTextShow { get; set; }
        public int procedureParameterId { get; set; }

        [ForeignKey("procedureParameterId")]
        [InverseProperty("itemSelect")]
        public virtual ProcedureParameter procedureParameter { get; set; }
    }
}