// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Action_ChungTu
    {
        [Key]
        public int IDx { get; set; }
        public int? PhienDangNhap_Id { get; set; }
        [StringLength(50)]
        public string MaMucDichChungTu { get; set; }
        public int? ChungTu_Id { get; set; }
        public int? ChungTuChiTiet_Id { get; set; }
        public int? Duoc_Id { get; set; }
        public int? SoLoNhap_Id { get; set; }
        [StringLength(150)]
        public string SoKiemSoat { get; set; }
        public int? DonViTinh_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongYeuCau { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongThucTe { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongDaXuat { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaMua { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaBan { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaVon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaThanhToan { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? TyLeVAT { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? GiaTriVAT { get; set; }
        public int? MienPhi { get; set; }
        public int? DaPhatSinhPhieuHoanTra { get; set; }
        public int? DaPhatSinhPhieuXuat { get; set; }
        public int? KhuyenMai { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaVonVAT { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? ThanhTienMua { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? ThanhTienVon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongBanDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? HanDung { get; set; }
        [StringLength(50)]
        public string ThaoTac { get; set; }
        public int? TrangThai { get; set; }
        public int? DuocTonKho_Id { get; set; }
        public int? NguonDuoc_Id { get; set; }

        [ForeignKey("ChungTu_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_ChungTu ChungTu { get; set; }
        [ForeignKey("ChungTuChiTiet_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_ChungTuChiTiet ChungTuChiTiet { get; set; }
        [ForeignKey("DonViTinh_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_DonViTinh DonViTinh { get; set; }
        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("DuocTonKho_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_DuocTonKho DuocTonKho { get; set; }
        [ForeignKey("NguonDuoc_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_Dictionary NguonDuoc { get; set; }
        [ForeignKey("PhienDangNhap_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_PhienDangNhap PhienDangNhap { get; set; }
        [ForeignKey("SoLoNhap_Id")]
        [InverseProperty("K_Action_ChungTu")]
        public virtual K_ChungTuSoLoNhap SoLoNhap { get; set; }
    }
}