// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Action
    {
        [Key]
        public int IDx { get; set; }
        public int? PhienDangNhap_Id { get; set; }
        public int? CLSYeuCau_Id { get; set; }
        public int? DichVu_Id { get; set; }
        [StringLength(50)]
        public string ThaoTac { get; set; }
        public int? TrangThai { get; set; }

        [ForeignKey("CLSYeuCau_Id")]
        [InverseProperty("K_Action")]
        public virtual K_CLSYeuCau CLSYeuCau { get; set; }
        [ForeignKey("DichVu_Id")]
        [InverseProperty("K_Action")]
        public virtual K_DichVu DichVu { get; set; }
        [ForeignKey("PhienDangNhap_Id")]
        [InverseProperty("K_Action")]
        public virtual K_PhienDangNhap PhienDangNhap { get; set; }
    }
}