// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_BacSi
    {
        public K_BacSi()
        {
            DM_BacSi_PhongKham_User = new HashSet<DM_BacSi_PhongKham_User>();
            DM_ICD_Common = new HashSet<DM_ICD_Common>();
            K_CLSKetQua = new HashSet<K_CLSKetQua>();
            K_CLSKetQua_CDHA = new HashSet<K_CLSKetQua_CDHA>();
        }

        [Key]
        public int BacSi_Id { get; set; }
        [StringLength(50)]
        public string TenBacSi { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("BacSi")]
        public virtual ICollection<DM_BacSi_PhongKham_User> DM_BacSi_PhongKham_User { get; set; }
        [InverseProperty("BacSi")]
        public virtual ICollection<DM_ICD_Common> DM_ICD_Common { get; set; }
        [InverseProperty("BacSiKetLuan")]
        public virtual ICollection<K_CLSKetQua> K_CLSKetQua { get; set; }
        [InverseProperty("BacSiKetLuan")]
        public virtual ICollection<K_CLSKetQua_CDHA> K_CLSKetQua_CDHA { get; set; }
    }
}