// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_BenhVien
    {
        public K_BenhVien()
        {
            K_Users = new HashSet<K_Users>();
        }

        [Key]
        public int BenhVien_Id { get; set; }
        [StringLength(50)]
        public string MaBenhVien { get; set; }
        [StringLength(500)]
        public string TenBenhVien { get; set; }
        [StringLength(500)]
        public string DiaChi1 { get; set; }
        [StringLength(500)]
        public string DiaChi2 { get; set; }
        [StringLength(500)]
        public string DiaChi3 { get; set; }
        [StringLength(50)]
        public string SoDienThoai1 { get; set; }
        [StringLength(50)]
        public string SoDienThoai2 { get; set; }
        [StringLength(50)]
        public string SoDienThoai3 { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("BenhVien")]
        public virtual ICollection<K_Users> K_Users { get; set; }
    }
}