// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_BenhNhan
    {
        public K_BenhNhan()
        {
            K_CLSKetQua = new HashSet<K_CLSKetQua>();
            K_CLSKetQua_CDHA = new HashSet<K_CLSKetQua_CDHA>();
            K_CLSYeuCau = new HashSet<K_CLSYeuCau>();
            K_ChungTu = new HashSet<K_ChungTu>();
            K_HoaDon = new HashSet<K_HoaDon>();
            K_KhamBenh = new HashSet<K_KhamBenh>();
            K_SoTiemChung = new HashSet<K_SoTiemChung>();
            K_TiepNhan = new HashSet<K_TiepNhan>();
            XetNghiemFile = new HashSet<XetNghiemFile>();
        }

        [Key]
        public int BenhNhan_Id { get; set; }
        [StringLength(50)]
        public string MaYTe { get; set; }
        [StringLength(50)]
        public string SoVaoVien { get; set; }
        [StringLength(500)]
        public string TenBenhNhan { get; set; }
        [StringLength(10)]
        public string GioiTinh { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgaySinh { get; set; }
        public int? NamSinh { get; set; }
        [StringLength(50)]
        public string SoDienThoai { get; set; }
        [StringLength(50)]
        public string CMND { get; set; }
        [StringLength(500)]
        public string DiaChiChiTiet { get; set; }
        [StringLength(150)]
        public string XaPhuong { get; set; }
        [StringLength(50)]
        public string QuanHuyen { get; set; }
        [StringLength(50)]
        public string TinhThanh { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }
        public string LinkHinhAnh { get; set; }
        [StringLength(250)]
        public string Zalo_Id { get; set; }
        public int? DanToc { get; set; }
        [StringLength(250)]
        public string MaSoThue { get; set; }
        [StringLength(500)]
        public string TenDonVi { get; set; }
        public int? BNNuocNgoai { get; set; }

        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_CLSKetQua> K_CLSKetQua { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_CLSKetQua_CDHA> K_CLSKetQua_CDHA { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_CLSYeuCau> K_CLSYeuCau { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_ChungTu> K_ChungTu { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_HoaDon> K_HoaDon { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_KhamBenh> K_KhamBenh { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_SoTiemChung> K_SoTiemChung { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<K_TiepNhan> K_TiepNhan { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<XetNghiemFile> XetNghiemFile { get; set; }
    }
}