// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_BookingTiemChung
    {
        [Key]
        public int IDx { get; set; }
        public int? PhienDangNhap_Id { get; set; }
        public int? TiepNhan_Id { get; set; }
        public int? TiemChung_Id { get; set; }
        public int? Duoc_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuong { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGia { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? ThanhTien { get; set; }
        public int? MuiTiem_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTiem { get; set; }
        [StringLength(10)]
        public string XacNhanTiem { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayHenTiem { get; set; }
        [StringLength(500)]
        public string GhiChu { get; set; }
        [StringLength(50)]
        public string ThaoTac { get; set; }
        public int? TrangThai { get; set; }
        public int? SoTiemChung_Id { get; set; }
        public int? TiepNhan_IdDaTiem { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayHenSMS { get; set; }
        [StringLength(15)]
        public string ChuyenKhoKhach { get; set; }
        public int? SoLoNhap_Id { get; set; }
        public int? LaVacXinNhaThuoc { get; set; }

        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_BookingTiemChung")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("PhienDangNhap_Id")]
        [InverseProperty("K_BookingTiemChung")]
        public virtual K_PhienDangNhap PhienDangNhap { get; set; }
        [ForeignKey("SoTiemChung_Id")]
        [InverseProperty("K_BookingTiemChung")]
        public virtual K_SoTiemChung SoTiemChung { get; set; }
        [ForeignKey("TiemChung_Id")]
        [InverseProperty("K_BookingTiemChung")]
        public virtual K_TiemChung TiemChung { get; set; }
        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_BookingTiemChung")]
        public virtual K_TiepNhan TiepNhan { get; set; }
    }
}