// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_ChungTuChiTiet
    {
        public K_ChungTuChiTiet()
        {
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_DuocTonKho = new HashSet<K_DuocTonKho>();
            K_DuocTonKhoBooking = new HashSet<K_DuocTonKhoBooking>();
        }

        [Key]
        public int ChungTuChiTiet_Id { get; set; }
        public int? ChungTu_Id { get; set; }
        public int? Duoc_Id { get; set; }
        public int? SoLoNhap_Id { get; set; }
        [StringLength(20)]

        public string SoKiemSoat { get; set; }
        [StringLength(20)]

        public string SoVisa { get; set; }
        public int? DonViTinh_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? SoLuongYeuCau { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? SoLuongThucTe { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? SoLuongDaXuat { get; set; }
        [StringLength(3)]
        public string TienTe_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? TyGia { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaMua { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaBan { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaVon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaThanhToan { get; set; }
        [StringLength(20)]

        public string SoQuyen { get; set; }
        [StringLength(20)]

        public string SoHoaDonVAT { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(5,2)]
        public decimal? TyLeVAT { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriVAT { get; set; }
        public int? MienPhi { get; set; }
        public int? LyDoMienPhi_Id { get; set; }
        [StringLength(20)]

        public string SoChungTuKeToan { get; set; }
        [StringLength(20)]

        public string SoChungTuTienMat { get; set; }
        [StringLength(20)]

        public string TrangThai { get; set; }
        public int? DaPhatSinhPhieuXuat { get; set; }
        public int? DaPhatSinhPhieuHoanTra { get; set; }
        public int? KhuyenMai { get; set; }
        public int? DonDatHang_Id { get; set; }
        [StringLength(255)]
        public string GhiChuChiTiet { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public int? NguonHang_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaVonVAT { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(27,4)]
        public decimal? ThanhTienMua { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(27,4)]
        public decimal? ThanhTienVon { get; set; }
        public int? IsTachLo { get; set; }
        public int? DonViTinhBanDau_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? SoLuongBanDau { get; set; }
        public int? Huy { get; set; }
        public int? DuocTonKhoYeuCau_Id { get; set; }

        [ForeignKey("ChungTu_Id")]
        [InverseProperty("K_ChungTuChiTiet")]
        public virtual K_ChungTu ChungTu { get; set; }
        [ForeignKey("DonViTinh_Id")]
        [InverseProperty("K_ChungTuChiTiet")]
        public virtual K_DonViTinh DonViTinh { get; set; }
        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_ChungTuChiTiet")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("DuocTonKhoYeuCau_Id")]
        [InverseProperty("K_ChungTuChiTiet")]
        public virtual K_DuocTonKho DuocTonKhoYeuCau { get; set; }
        [ForeignKey("SoLoNhap_Id")]
        [InverseProperty("K_ChungTuChiTiet")]
        public virtual K_ChungTuSoLoNhap SoLoNhap { get; set; }
        [InverseProperty("ChungTuChiTiet")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("ChungTuChiTiet")]
        public virtual ICollection<K_DuocTonKho> K_DuocTonKho { get; set; }
        [InverseProperty("ChungTuChiTiet")]
        public virtual ICollection<K_DuocTonKhoBooking> K_DuocTonKhoBooking { get; set; }
    }
}