// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_ChungTu
    {
        public K_ChungTu()
        {
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_ChungTuChiTiet = new HashSet<K_ChungTuChiTiet>();
        }

        [Key]
        public int ChungTu_Id { get; set; }
        [Required]
        [StringLength(30)]

        public string MaChungTu { get; set; }
        [Required]
        [StringLength(10)]

        public string SoChungTu { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime NgayChungTu { get; set; }
        [Required]
        [StringLength(1)]

        public string LoaiChungTu { get; set; }
        public int? MucDichChungTu_Id { get; set; }
        public int? KhoXuat_Id { get; set; }
        public int? NguoiGiao_Id { get; set; }
        [StringLength(30)]
        public string NguoiGiao { get; set; }
        public int? KhoNhap_Id { get; set; }
        public int? NguoiNhan_Id { get; set; }
        [StringLength(30)]
        public string NguoiNhan { get; set; }
        public int? NguoiKiemTra_Id { get; set; }
        [StringLength(30)]
        public string NguoiKiemTra { get; set; }
        public int? NguoiDuyet_Id { get; set; }
        [StringLength(30)]
        public string NguoiDuyet { get; set; }
        public int? KeToanTruong_Id { get; set; }
        [StringLength(30)]
        public string KeToanTruong { get; set; }
        public int? ThuKho_Id { get; set; }
        [StringLength(30)]
        public string ThuKho { get; set; }
        [StringLength(20)]

        public string SoSeri { get; set; }
        [StringLength(20)]

        public string SoHoaDon { get; set; }
        [StringLength(255)]
        public string DienGiai { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTri { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriThanhToan { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(5,2)]
        public decimal? TyLeVat { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriVat { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(5,2)]
        public decimal? ThueSuat { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriThue { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(5,2)]
        public decimal? TyleChietKhau { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriChietKhau { get; set; }
        [StringLength(3)]
        public string TienTe_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(9,2)]
        public decimal? TyGia { get; set; }
        [StringLength(15)]

        public string SoChungTuGoc { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? NgayChungTuGoc { get; set; }
        public int? NhaCungCap_Id { get; set; }
        public int? HinhThucThanhToan_Id { get; set; }
        public int? NguonDuoc_Id { get; set; }
        public int? ChungTuLienQuan_Id { get; set; }
        public int? KhamBenh_Id { get; set; }
        public int? ToaThuocNoiTru_Id { get; set; }
        public int? BenhAn_Id { get; set; }
        public int DaNhanThuoc { get; set; }
        public int? NguoiNhap_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayNhap { get; set; }
        [StringLength(20)]

        public string TrangThai { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public int? PhieuLinh_Id { get; set; }
        [StringLength(100)]
        public string DienGiaiNghiepVuPhatSinh { get; set; }
        public int? DonViGiao_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(5,2)]
        public decimal? TyLeVATNhapKhau { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(26,2)]
        public decimal? GiaTriVATNhapKhau { get; set; }
        [StringLength(20)]

        public string SoSeriNuocNgoai { get; set; }
        [StringLength(20)]

        public string SoHoaDonNuocNgoai { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? NgayHoaDonNuocNgoai { get; set; }
        public int? KhoSuDung_Id { get; set; }
        [StringLength(1)]

        public string LoaiVatTu_Id { get; set; }
        public int? BenhNhan_Id { get; set; }
        [StringLength(40)]
        public string TenBenhNhan { get; set; }
        public int? GioiTinh { get; set; }
        public short? NamSinh { get; set; }
        [StringLength(200)]
        public string DiaChi { get; set; }
        [StringLength(30)]

        public string SoDienThoai { get; set; }
        public int? BacSiGioiThieu_Id { get; set; }
        public int? DoiTuong_Id { get; set; }
        public int? IDChuyen { get; set; }
        [StringLength(50)]

        public string ChungTuKeToan { get; set; }
        public int? Status { get; set; }
        public int? Transfer_VienPhi_Id { get; set; }
        public int? PhongBan_Id { get; set; }
        public int? BacSi_Id { get; set; }
        [StringLength(25)]

        public string TKNo { get; set; }
        [StringLength(25)]

        public string TKCo { get; set; }
        [StringLength(30)]

        public string MaChungTuRef { get; set; }
        [StringLength(2)]

        public string LoaiChungTuRef { get; set; }
        public int? PhieuLinhCanTru_Id { get; set; }
        public int? KhoThucHien_Id { get; set; }
        public int? KhoDoiUng_Id { get; set; }
        public bool? BHYT { get; set; }
        public bool? VienPhi { get; set; }
        [StringLength(20)]
        public string MauSo { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("BenhNhan_Id")]
        [InverseProperty("K_ChungTu")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [ForeignKey("HinhThucThanhToan_Id")]
        [InverseProperty("K_ChungTuHinhThucThanhToan")]
        public virtual K_Dictionary HinhThucThanhToan { get; set; }
        [ForeignKey("KhamBenh_Id")]
        [InverseProperty("K_ChungTu")]
        public virtual K_KhamBenh KhamBenh { get; set; }
        [ForeignKey("KhoNhap_Id")]
        [InverseProperty("K_ChungTuKhoNhap")]
        public virtual K_KhoDuoc KhoNhap { get; set; }
        [ForeignKey("KhoXuat_Id")]
        [InverseProperty("K_ChungTuKhoXuat")]
        public virtual K_KhoDuoc KhoXuat { get; set; }
        [ForeignKey("MucDichChungTu_Id")]
        [InverseProperty("K_ChungTuMucDichChungTu")]
        public virtual K_Dictionary MucDichChungTu { get; set; }
        [ForeignKey("NguonDuoc_Id")]
        [InverseProperty("K_ChungTuNguonDuoc")]
        public virtual K_Dictionary NguonDuoc { get; set; }
        [ForeignKey("NhaCungCap_Id")]
        [InverseProperty("K_ChungTu")]
        public virtual K_DM_NhaCungCap NhaCungCap { get; set; }
        [InverseProperty("ChungTu")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("ChungTu")]
        public virtual ICollection<K_ChungTuChiTiet> K_ChungTuChiTiet { get; set; }
    }
}