// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_CLSKetQua_CDHAHinhAnh
    {
        [Key]
        public int CLSKetQuaHinhAnh_Id { get; set; }
        public int? CLSKetQua_Id { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Link { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("CLSKetQua_Id")]
        [InverseProperty("K_CLSKetQua_CDHAHinhAnh")]
        public virtual K_CLSKetQua CLSKetQua { get; set; }
    }
}