// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_CLSYeuCau
    {
        public K_CLSYeuCau()
        {
            InverseCLSYeuCau_Cha = new HashSet<K_CLSYeuCau>();
            K_Action = new HashSet<K_Action>();
            K_CLSKetQua_CDHA = new HashSet<K_CLSKetQua_CDHA>();
            K_HoaDonChiTiet = new HashSet<K_HoaDonChiTiet>();
            K_KetQuaGiaiPhauBenh = new HashSet<K_KetQuaGiaiPhauBenh>();
            K_KhamBenh = new HashSet<K_KhamBenh>();
        }

        [Key]
        public int CLSYeuCau_Id { get; set; }
        [StringLength(150)]
        public string SoPhieuYeuCau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayYeuCau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianYeuCau { get; set; }
        public int? TiepNhan_Id { get; set; }
        public int? BenhNhan_id { get; set; }
        public int? DichVu_Id { get; set; }
        public int? SoLuong { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaDichVu { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? ThanhTienDichVu { get; set; }
        public int? DuocPhepThucHien { get; set; }
        public int? DaThanhToan { get; set; }
        [StringLength(150)]
        public string TrangThai { get; set; }
        public int? NguoiChiDinh { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }
        public int? NguoiLayMau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayLaymau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianLayMau { get; set; }
        [StringLength(50)]
        public string SoLuongOng { get; set; }
        [StringLength(50)]
        public string SID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayThucHien { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianThucHien { get; set; }
        [StringLength(500)]
        public string KetQua { get; set; }
        public int? CLSYeuCau_Cha_Id { get; set; }
        public int? ChonIn { get; set; }
        //[StringLength(500)]
        //public string TenVo { get; set; }
        //public int? NamSinhVo { get; set; }
        //public int? NoiLayMauCSYT { get; set; }
        //public int? NoiLayMauNha { get; set; }
        //[Column(TypeName = "datetime")]
        //public DateTime? NgayNhanMau { get; set; }
        //[Column(TypeName = "datetime")]
        //public DateTime? ThoiGianNhanMau { get; set; }
        //[Column(TypeName = "ntext")]
        //public string NhanXetKhac { get; set; }
        //[StringLength(200)]
        //public string label13 { get; set; }
        //[StringLength(200)]
        //public string label14 { get; set; }
        //public int? checkBox1 { get; set; }
        public int? NoiThucHien_Id { get; set; }

        [ForeignKey("BenhNhan_id")]
        [InverseProperty("K_CLSYeuCau")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [ForeignKey("CLSYeuCau_Cha_Id")]
        [InverseProperty("InverseCLSYeuCau_Cha")]
        public virtual K_CLSYeuCau CLSYeuCau_Cha { get; set; }
        [ForeignKey("DichVu_Id")]
        [InverseProperty("K_CLSYeuCau")]
        public virtual K_DichVu DichVu { get; set; }
        [ForeignKey("NoiThucHien_Id")]
        [InverseProperty("K_CLSYeuCau")]
        public virtual K_PhongBan NoiThucHien { get; set; }
        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_CLSYeuCau")]
        public virtual K_TiepNhan TiepNhan { get; set; }
        [InverseProperty("CLSYeuCau_Cha")]
        public virtual ICollection<K_CLSYeuCau> InverseCLSYeuCau_Cha { get; set; }
        [InverseProperty("CLSYeuCau")]
        public virtual ICollection<K_Action> K_Action { get; set; }
        [InverseProperty("CLSYeuCau")]
        public virtual ICollection<K_CLSKetQua_CDHA> K_CLSKetQua_CDHA { get; set; }
        [InverseProperty("CLSYeuCau")]
        public virtual ICollection<K_HoaDonChiTiet> K_HoaDonChiTiet { get; set; }
        [InverseProperty("CLSYeuCau")]
        public virtual ICollection<K_KetQuaGiaiPhauBenh> K_KetQuaGiaiPhauBenh { get; set; }
        [InverseProperty("CLSYeuCau")]
        public virtual ICollection<K_KhamBenh> K_KhamBenh { get; set; }
    }
}