// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Dictionary
    {
        public K_Dictionary()
        {
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_ChungTuHinhThucThanhToan = new HashSet<K_ChungTu>();
            K_ChungTuMucDichChungTu = new HashSet<K_ChungTu>();
            K_ChungTuNguonDuoc = new HashSet<K_ChungTu>();
            K_ChungTuSoLoNhap = new HashSet<K_ChungTuSoLoNhap>();
            K_DuocTonKho = new HashSet<K_DuocTonKho>();
            K_TiemChungMuiTiem = new HashSet<K_TiemChung>();
            K_TiemChungPhanUngPhuTaiCho = new HashSet<K_TiemChung>();
            K_TiemChungPhanUngPhuToanThan = new HashSet<K_TiemChung>();
        }

        [Key]
        public int Dictionary_Id { get; set; }
        [StringLength(250)]
        public string Dictionary_Code { get; set; }
        public int? Dictionary_Name_Id { get; set; }
        [StringLength(500)]
        public string Dictionary_Name { get; set; }
        [StringLength(500)]
        public string DienGiai1 { get; set; }
        [StringLength(500)]
        public string DienGiai2 { get; set; }
        [StringLength(500)]
        public string DienGiai3 { get; set; }
        [StringLength(500)]
        public string DienGiai4 { get; set; }
        [StringLength(500)]
        public string DienGiai5 { get; set; }
        public int? TamNgung { get; set; }
        public int? Huy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }

        [InverseProperty("NguonDuoc")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("HinhThucThanhToan")]
        public virtual ICollection<K_ChungTu> K_ChungTuHinhThucThanhToan { get; set; }
        [InverseProperty("MucDichChungTu")]
        public virtual ICollection<K_ChungTu> K_ChungTuMucDichChungTu { get; set; }
        [InverseProperty("NguonDuoc")]
        public virtual ICollection<K_ChungTu> K_ChungTuNguonDuoc { get; set; }
        [InverseProperty("NguonDuoc")]
        public virtual ICollection<K_ChungTuSoLoNhap> K_ChungTuSoLoNhap { get; set; }
        [InverseProperty("NguonNhapHang")]
        public virtual ICollection<K_DuocTonKho> K_DuocTonKho { get; set; }
        [InverseProperty("MuiTiem")]
        public virtual ICollection<K_TiemChung> K_TiemChungMuiTiem { get; set; }
        [InverseProperty("PhanUngPhuTaiCho")]
        public virtual ICollection<K_TiemChung> K_TiemChungPhanUngPhuTaiCho { get; set; }
        [InverseProperty("PhanUngPhuToanThan")]
        public virtual ICollection<K_TiemChung> K_TiemChungPhanUngPhuToanThan { get; set; }
    }
}