// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DM_Duoc
    {
        public K_DM_Duoc()
        {
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_BookingDuoc = new HashSet<K_BookingDuoc>();
            K_BookingTiemChung = new HashSet<K_BookingTiemChung>();
            K_ChungTuChiTiet = new HashSet<K_ChungTuChiTiet>();
            K_ChungTuSoLoNhap = new HashSet<K_ChungTuSoLoNhap>();
            K_DM_Duoc_DonGia = new HashSet<K_DM_Duoc_DonGia>();
            K_DM_Duoc_DonGia_His = new HashSet<K_DM_Duoc_DonGia_His>();
            K_DuocTonKho = new HashSet<K_DuocTonKho>();
            K_MapGoiVacxinMauVoiDuoc = new HashSet<K_MapGoiVacxinMauVoiDuoc>();
            K_MapToaThuocMauVoiDuoc = new HashSet<K_MapToaThuocMauVoiDuoc>();
            K_TiemChung = new HashSet<K_TiemChung>();
            K_ToaThuoc = new HashSet<K_ToaThuoc>();
        }

        [Key]
        public int Duoc_Id { get; set; }
        [StringLength(150)]
        public string MaDuoc { get; set; }
        [StringLength(250)]
        public string TenDuoc { get; set; }
        public string DonViTinh { get; set; }
        public int? DonViTinh_Id { get; set; }
        public string HangSanXuat { get; set; }
        public int? HangSanXuat_Id { get; set; }
        public string QuocGia { get; set; }
        public int? QuocGia_Id { get; set; }
        public string TenDuocDayDu { get; set; }
        public string TenKhongDau { get; set; }
        public string TenHoatChat { get; set; }
        public string CachSuDung { get; set; }
        [StringLength(250)]
        public string HamLuong { get; set; }
        [StringLength(250)]
        public string CongDung { get; set; }
        public int? LoaiDuoc_Id { get; set; }
        [StringLength(50)]
        public string PhanLoaiDuoc { get; set; }
        [StringLength(250)]
        public string DuongDung { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        [StringLength(250)]
        public string MaDuocQuocGia { get; set; }
        [StringLength(500)]
        public string DienGiai { get; set; }
        [StringLength(500)]
        public string SoThamChieu { get; set; }
        public string GhiChu1 { get; set; }
        public string GhiChu2 { get; set; }
        public string GhiChu3 { get; set; }
        public int? Huy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateStart { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateEnd { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongNhapVao { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongTon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaVon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGia { get; set; }
        public int? KhoQuanLy_ID { get; set; }
        public int? KhoKhoaTam_ID { get; set; }
        public int? PhacDo_ID { get; set; }
        [StringLength(10)]

        public string MaLoaiVacXin { get; set; }

        [ForeignKey("DonViTinh_Id")]
        [InverseProperty("K_DM_Duoc")]
        public virtual K_DonViTinh DonViTinhNavigation { get; set; }
        [ForeignKey("KhoKhoaTam_ID")]
        [InverseProperty("K_DM_DuocKhoKhoaTam")]
        public virtual K_KhoDuoc KhoKhoaTam { get; set; }
        [ForeignKey("KhoQuanLy_ID")]
        [InverseProperty("K_DM_DuocKhoQuanLy")]
        public virtual K_KhoDuoc KhoQuanLy { get; set; }
        [ForeignKey("LoaiDuoc_Id")]
        [InverseProperty("K_DM_Duoc")]
        public virtual K_LoaiDuoc LoaiDuoc { get; set; }
        [ForeignKey("MaLoaiVacXin")]
        [InverseProperty("K_DM_Duoc")]
        public virtual K_Dm_LoaiVacXin MaLoaiVacXinNavigation { get; set; }
        [ForeignKey("PhacDo_ID")]
        [InverseProperty("K_DM_Duoc")]
        public virtual K_DM_PhacDo PhacDo { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_BookingDuoc> K_BookingDuoc { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_BookingTiemChung> K_BookingTiemChung { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_ChungTuChiTiet> K_ChungTuChiTiet { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_ChungTuSoLoNhap> K_ChungTuSoLoNhap { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_DM_Duoc_DonGia> K_DM_Duoc_DonGia { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_DM_Duoc_DonGia_His> K_DM_Duoc_DonGia_His { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_DuocTonKho> K_DuocTonKho { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_MapGoiVacxinMauVoiDuoc> K_MapGoiVacxinMauVoiDuoc { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_MapToaThuocMauVoiDuoc> K_MapToaThuocMauVoiDuoc { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_TiemChung> K_TiemChung { get; set; }
        [InverseProperty("Duoc")]
        public virtual ICollection<K_ToaThuoc> K_ToaThuoc { get; set; }
    }
}