// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Dm_LoaiVacXin
    {
        public K_Dm_LoaiVacXin()
        {
            K_DM_Duoc = new HashSet<K_DM_Duoc>();
        }

        [Key]
        [StringLength(10)]

        public string MaLoaiVacXin { get; set; }
        [Required]
        [StringLength(50)]
        public string TenLoaiVacXin { get; set; }
        [StringLength(200)]
        public string GhiChu { get; set; }
        public bool KichHoat { get; set; }

        [InverseProperty("MaLoaiVacXinNavigation")]
        public virtual ICollection<K_DM_Duoc> K_DM_Duoc { get; set; }
    }
}