// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DM_Duoc_DonGia
    {
        [Key]
        public int Duoc_DonGia_Id { get; set; }
        public int? BangGia_Id { get; set; }
        public int Duoc_Id { get; set; }
        public int? LoaiGia_Id { get; set; }
        [StringLength(3)]
        public string TienTe_Id { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,3)]
        public decimal? DonGia { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(5,2)]
        public decimal? TyLeVAT { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? GiaTriVAT { get; set; }
        [StringLength(20)]

        public string TrangThai { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? GiaVonTB { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? TyLeLai { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaBanGoc_SauVAT { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaBanGoc_TruocVAT { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,2)]
        public decimal? GiaVonGanNhat { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,3)]
        public decimal? DonGiaThayDoi { get; set; }
        public int? Huy { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,3)]
        public decimal? CongTiem { get; set; }

        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_DM_Duoc_DonGia")]
        public virtual K_DM_Duoc Duoc { get; set; }
    }
}