// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DM_PhacDo
    {
        public K_DM_PhacDo()
        {
            K_DM_Duoc = new HashSet<K_DM_Duoc>();
        }

        [Key]
        public int PhacDo_ID { get; set; }
        [StringLength(50)]
        public string MaPhacDo { get; set; }
        [StringLength(500)]
        public string TenPhacDo { get; set; }
        [StringLength(2000)]
        public string GhiChu { get; set; }
        public int? TamNgung { get; set; }

        [InverseProperty("PhacDo")]
        public virtual ICollection<K_DM_Duoc> K_DM_Duoc { get; set; }
    }
}