// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DM_Duoc_DonGia_His
    {
        [Key]
        public int Idx { get; set; }
        public int? Duoc_DonGia_Id { get; set; }
        public int Duoc_Id { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,3)]
        public decimal? DonGiaCu { get; set; }
        [Column(TypeName = "decimal")]
        [DecimalPrecision(18,3)]
        public decimal? DonGiaMoi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }

        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_DM_Duoc_DonGia_His")]
        public virtual K_DM_Duoc Duoc { get; set; }
    }
}