// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DM_NhaCungCap
    {
        public K_DM_NhaCungCap()
        {
            K_ChungTu = new HashSet<K_ChungTu>();
        }

        [Key]
        public int NhaCungCap_Id { get; set; }
        [StringLength(20)]

        public string MaNhaCungCap { get; set; }
        [StringLength(200)]
        public string TenNhaCungCap { get; set; }
        [StringLength(200)]
        public string TenNhaCungCap_En { get; set; }
        [StringLength(200)]
        public string TenNhaCungCap_Ru { get; set; }
        [StringLength(200)]
        public string DiaChi { get; set; }
        [StringLength(30)]
        public string DienThoai { get; set; }
        [StringLength(30)]
        public string Fax { get; set; }
        [StringLength(30)]
        public string Email { get; set; }
        [StringLength(20)]
        public string MaSoThue { get; set; }
        [StringLength(30)]
        public string GiamDoc { get; set; }
        [StringLength(30)]
        public string NguoiLienHe { get; set; }
        public bool? NuocNgoai { get; set; }
        public bool NhaNuoc { get; set; }
        public bool TamNgung { get; set; }
        [StringLength(200)]
        public string TenKhongDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public bool PH_Duoc { get; set; }
        public bool PH_NHM { get; set; }
        public bool PH_TaiSan { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("NhaCungCap")]
        public virtual ICollection<K_ChungTu> K_ChungTu { get; set; }
    }
}