// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DonViTinh
    {
        public K_DonViTinh()
        {
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_ChungTuChiTiet = new HashSet<K_ChungTuChiTiet>();
            K_DM_Duoc = new HashSet<K_DM_Duoc>();
        }

        [Key]
        public int DonViTinh_Id { get; set; }
        [StringLength(50)]
        public string MaDonViTinh { get; set; }
        [StringLength(250)]
        public string TenDonViTinh { get; set; }
        [StringLength(50)]
        public string LoaiThuoc { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? GiaTriQuyDoi { get; set; }
        public int? TamNgung { get; set; }
        public int? Huy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }

        [InverseProperty("DonViTinh")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("DonViTinh")]
        public virtual ICollection<K_ChungTuChiTiet> K_ChungTuChiTiet { get; set; }
        [InverseProperty("DonViTinhNavigation")]
        public virtual ICollection<K_DM_Duoc> K_DM_Duoc { get; set; }
    }
}