// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DuocTonKho
    {
        public K_DuocTonKho()
        {
            InverseDuocTonKhoYeuCau = new HashSet<K_DuocTonKho>();
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_ChungTuChiTiet = new HashSet<K_ChungTuChiTiet>();
            K_DuocTonKhoBookingDuocTonKho = new HashSet<K_DuocTonKhoBooking>();
            K_DuocTonKhoBookingDuocTonKhoYeuCau = new HashSet<K_DuocTonKhoBooking>();
            K_TiemChung = new HashSet<K_TiemChung>();
        }

        [Key]
        public int DuocTonKho_Id { get; set; }
        public int? KhoDuoc_Id { get; set; }
        public int? Duoc_Id { get; set; }
        public int? NguonNhapHang_Id { get; set; }
        public int? SoLoNhap_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGiaMua { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuong { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongGoc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public int? Huy { get; set; }
        public int? SuDung { get; set; }
        public int? DuocTonKhoYeuCau_Id { get; set; }
        public int? ChungTuChiTiet_Id { get; set; }

        [ForeignKey("ChungTuChiTiet_Id")]
        [InverseProperty("K_DuocTonKho")]
        public virtual K_ChungTuChiTiet ChungTuChiTiet { get; set; }
        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_DuocTonKho")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("DuocTonKhoYeuCau_Id")]
        [InverseProperty("InverseDuocTonKhoYeuCau")]
        public virtual K_DuocTonKho DuocTonKhoYeuCau { get; set; }
        [ForeignKey("KhoDuoc_Id")]
        [InverseProperty("K_DuocTonKho")]
        public virtual K_KhoDuoc KhoDuoc { get; set; }
        [ForeignKey("NguonNhapHang_Id")]
        [InverseProperty("K_DuocTonKho")]
        public virtual K_Dictionary NguonNhapHang { get; set; }
        [ForeignKey("SoLoNhap_Id")]
        [InverseProperty("K_DuocTonKho")]
        public virtual K_ChungTuSoLoNhap SoLoNhap { get; set; }
        [InverseProperty("DuocTonKhoYeuCau")]
        public virtual ICollection<K_DuocTonKho> InverseDuocTonKhoYeuCau { get; set; }
        [InverseProperty("DuocTonKho")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("DuocTonKhoYeuCau")]
        public virtual ICollection<K_ChungTuChiTiet> K_ChungTuChiTiet { get; set; }
        [InverseProperty("DuocTonKho")]
        public virtual ICollection<K_DuocTonKhoBooking> K_DuocTonKhoBookingDuocTonKho { get; set; }
        [InverseProperty("DuocTonKhoYeuCau")]
        public virtual ICollection<K_DuocTonKhoBooking> K_DuocTonKhoBookingDuocTonKhoYeuCau { get; set; }
        [InverseProperty("DuocTonKho")]
        public virtual ICollection<K_TiemChung> K_TiemChung { get; set; }
    }
}