// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_DuocTonKhoBooking
    {
        [Key]
        public int Idx { get; set; }
        public int? PhienDangNhap_Id { get; set; }
        public int? ChungTuChiTiet_Id { get; set; }
        public int? DuocTonKho_Id { get; set; }
        public int? DuocTonKhoYeuCau_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18, 2)]
        public decimal? SoLuong { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuongYeuCau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        [StringLength(50)]
        public string ThaoTac { get; set; }
        public int? TrangThai { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayHieuLuc { get; set; }

        [ForeignKey("ChungTuChiTiet_Id")]
        [InverseProperty("K_DuocTonKhoBooking")]
        public virtual K_ChungTuChiTiet ChungTuChiTiet { get; set; }
        [ForeignKey("DuocTonKho_Id")]
        [InverseProperty("K_DuocTonKhoBookingDuocTonKho")]
        public virtual K_DuocTonKho DuocTonKho { get; set; }
        [ForeignKey("DuocTonKhoYeuCau_Id")]
        [InverseProperty("K_DuocTonKhoBookingDuocTonKhoYeuCau")]
        public virtual K_DuocTonKho DuocTonKhoYeuCau { get; set; }
        [ForeignKey("PhienDangNhap_Id")]
        [InverseProperty("K_DuocTonKhoBooking")]
        public virtual K_PhienDangNhap PhienDangNhap { get; set; }
    }
}