// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_HoaDon
    {
        public K_HoaDon()
        {
            K_HoaDonChiTiet = new HashSet<K_HoaDonChiTiet>();
            ZaloFile = new HashSet<ZaloFile>();
        }

        [Key]
        public int HoaDon_Id { get; set; }
        [StringLength(250)]
        public string SoHoaDon { get; set; }
        [StringLength(250)]
        public string SoHoaDonVAT { get; set; }
        [StringLength(50)]
        public string LoaiHoaDon { get; set; }
        public int? TiepNhan_Id { get; set; }
        public int? BenhNhan_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayPhatSinh { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianPhatSinh { get; set; }
        public int? NoiPhatSinh_Id { get; set; }
        public int? NguoiLapHoaDon { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? GiaTriHoaDon { get; set; }
        public int? HinhThucThanhToan { get; set; }
        public int? HuyHoaDon { get; set; }
        public int? HoanTra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianTra { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        [StringLength(250)]
        public string MaSoThue { get; set; }
        [StringLength(500)]
        public string TenDonVi { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? GiamGia { get; set; }
        public int? GiamGiaTiLe { get; set; }
        [StringLength(250)]
        public string MaATM { get; set; }
        [StringLength(500)]
        public string LyDoHuyHoacHoanTra { get; set; }

        [ForeignKey("BenhNhan_Id")]
        [InverseProperty("K_HoaDon")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [ForeignKey("NoiPhatSinh_Id")]
        [InverseProperty("K_HoaDon")]
        public virtual K_PhongBan NoiPhatSinh { get; set; }
        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_HoaDon")]
        public virtual K_TiepNhan TiepNhan { get; set; }
        [InverseProperty("HoaDon")]
        public virtual ICollection<K_HoaDonChiTiet> K_HoaDonChiTiet { get; set; }
        [InverseProperty("HoaDon")]
        public virtual ICollection<ZaloFile> ZaloFile { get; set; }
    }
}