// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_KetQuaGiaiPhauBenh
    {
        [Key]
        public int KQ_GPB_Id { get; set; }
        public int? checkbox1 { get; set; }
        public int? checkbox2 { get; set; }
        public int? checkbox3 { get; set; }
        public int? checkbox4 { get; set; }
        public int? checkbox5 { get; set; }
        public int? checkbox6 { get; set; }
        public int? checkbox7 { get; set; }
        public int? checkbox8 { get; set; }
        public int? checkbox9 { get; set; }
        public int? checkbox10 { get; set; }
        public int? checkbox11 { get; set; }
        public int? checkbox12 { get; set; }
        public int? checkbox13 { get; set; }
        public int? checkbox14 { get; set; }
        public int? checkbox15 { get; set; }
        public int? checkbox16 { get; set; }
        public int? checkbox17 { get; set; }
        public int? checkbox18 { get; set; }
        public int? checkbox19 { get; set; }
        public int? checkbox20 { get; set; }
        public int? checkbox21 { get; set; }
        public int? checkbox22 { get; set; }
        public int? checkbox23 { get; set; }
        public int? checkbox24 { get; set; }
        public int? checkbox25 { get; set; }
        public int? checkbox26 { get; set; }
        public int? checkbox27 { get; set; }
        public int? checkbox28 { get; set; }
        public int? checkbox29 { get; set; }
        public int? checkbox30 { get; set; }
        public int? checkbox31 { get; set; }
        public int? checkbox32 { get; set; }
        public int? checkbox33 { get; set; }
        public int? checkbox34 { get; set; }
        public int? checkbox35 { get; set; }
        public int? checkbox36 { get; set; }
        public int? checkbox37 { get; set; }
        public int? checkbox38 { get; set; }
        public int? CLSKetQua_Id { get; set; }
        public int? CLSYeuCau_Id { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("CLSKetQua_Id")]
        [InverseProperty("K_KetQuaGiaiPhauBenh")]
        public virtual K_CLSKetQua CLSKetQua { get; set; }
        [ForeignKey("CLSYeuCau_Id")]
        [InverseProperty("K_KetQuaGiaiPhauBenh")]
        public virtual K_CLSYeuCau CLSYeuCau { get; set; }
    }
}