// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_KhoDuoc
    {
        public K_KhoDuoc()
        {
            K_ChungTuKhoNhap = new HashSet<K_ChungTu>();
            K_ChungTuKhoXuat = new HashSet<K_ChungTu>();
            K_DM_DuocKhoKhoaTam = new HashSet<K_DM_Duoc>();
            K_DM_DuocKhoQuanLy = new HashSet<K_DM_Duoc>();
            K_DuocTonKho = new HashSet<K_DuocTonKho>();
            K_PhienDangNhap = new HashSet<K_PhienDangNhap>();
        }

        [Key]
        public int KhoDuoc_Id { get; set; }
        [StringLength(10)]

        public string MaKho { get; set; }
        [StringLength(100)]
        public string TenKho { get; set; }
        public int? PhongBan_Id { get; set; }
        public int? LoaiKho_Id { get; set; }
        public bool? TamNgung { get; set; }
        [StringLength(100)]
        public string TenKhongDau { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat_Id { get; set; }
        public bool? QLNguon { get; set; }
        public bool? KhoDuoc { get; set; }
        public bool? KhoTaiSan { get; set; }
        public bool? KhoNHM { get; set; }
        public bool? KhoVPP { get; set; }
        public bool? KhoTTB { get; set; }
        public int? ChuyenKhoa_Id { get; set; }
        public int? CostCenter_Id { get; set; }
        public int? Huy { get; set; }
        public int? IsKhoCha { get; set; }
        public int? CapTren_Id { get; set; }

        [InverseProperty("KhoNhap")]
        public virtual ICollection<K_ChungTu> K_ChungTuKhoNhap { get; set; }
        [InverseProperty("KhoXuat")]
        public virtual ICollection<K_ChungTu> K_ChungTuKhoXuat { get; set; }
        [InverseProperty("KhoKhoaTam")]
        public virtual ICollection<K_DM_Duoc> K_DM_DuocKhoKhoaTam { get; set; }
        [InverseProperty("KhoQuanLy")]
        public virtual ICollection<K_DM_Duoc> K_DM_DuocKhoQuanLy { get; set; }
        [InverseProperty("KhoDuoc")]
        public virtual ICollection<K_DuocTonKho> K_DuocTonKho { get; set; }
        [InverseProperty("KhoDuoc")]
        public virtual ICollection<K_PhienDangNhap> K_PhienDangNhap { get; set; }
    }
}