// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_KhamSangLoc
    {
        [Key]
        public int KhamSangLoc_Id { get; set; }
        public int? TiepNhan_Id { get; set; }
        [StringLength(500)]
        public string HoTenBoMe { get; set; }
        [StringLength(50)]
        public string SoDienThoaiBoMe { get; set; }
        [StringLength(50)]
        public string CanNang { get; set; }
        [StringLength(10)]
        public string ThanNhiet { get; set; }
        [StringLength(10)]
        public string HA1 { get; set; }
        [StringLength(10)]
        public string HA2 { get; set; }
        public int? chkKSL1 { get; set; }
        public int? chkKSL2 { get; set; }
        public int? chkKSL3 { get; set; }
        public int? chkKSL4 { get; set; }
        public int? chkKSL5 { get; set; }
        public int? chkKSL6 { get; set; }
        public int? chkKSL7 { get; set; }
        public int? chkKSL8 { get; set; }
        public int? chkKSL9 { get; set; }
        public int? chkKSL10 { get; set; }
        public int? chkKSL11 { get; set; }
        public int? chkKSL12 { get; set; }
        public int? chkKSL13 { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_KhamSangLoc")]
        public virtual K_TiepNhan TiepNhan { get; set; }
    }
}