// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_KhamBenh
    {
        public K_KhamBenh()
        {
            K_BookingDuoc = new HashSet<K_BookingDuoc>();
            K_ChungTu = new HashSet<K_ChungTu>();
            K_ToaThuoc = new HashSet<K_ToaThuoc>();
            K_XacNhanHoanTatKham = new HashSet<K_XacNhanHoanTatKham>();
            ZaloFile = new HashSet<ZaloFile>();
        }

        [Key]
        public int KhamBenh_Id { get; set; }
        public int? TiepNhan_Id { get; set; }
        public int? BenhNhan_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayKham { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianKham { get; set; }
        public int? PhongKham_Id { get; set; }
        public int? BacSiKham { get; set; }
        [StringLength(50)]
        public string Mach { get; set; }
        [StringLength(50)]
        public string NhietDo { get; set; }
        [StringLength(50)]
        public string CanNang { get; set; }
        [StringLength(50)]
        public string ChieuCao { get; set; }
        [StringLength(50)]
        public string HuyetApCao { get; set; }
        [StringLength(50)]
        public string HuyetApThap { get; set; }
        [StringLength(50)]
        public string NhipTho { get; set; }
        [StringLength(50)]
        public string BMI { get; set; }
        public string TrieuChung { get; set; }
        public int? ICD_Id { get; set; }
        public string ChanDoan { get; set; }
        [Column(TypeName = "ntext")]
        public string KetLuan { get; set; }
        [Column(TypeName = "ntext")]
        public string LoiDan { get; set; }
        public int? CLSYeuCau_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }
        [StringLength(50)]
        public string SoThuTuToa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? HenTaiKham { get; set; }
        public string BenhKem_Id { get; set; }
        public string BenhKem_MaICD { get; set; }
        public string BenhKem_TenICD { get; set; }
        public bool? LaTiemChung { get; set; }

        [ForeignKey("BenhNhan_Id")]
        [InverseProperty("K_KhamBenh")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [ForeignKey("CLSYeuCau_Id")]
        [InverseProperty("K_KhamBenh")]
        public virtual K_CLSYeuCau CLSYeuCau { get; set; }
        [ForeignKey("ICD_Id")]
        [InverseProperty("K_KhamBenh")]
        public virtual DM_ICD ICD { get; set; }
        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_KhamBenh")]
        public virtual K_TiepNhan TiepNhan { get; set; }
        [InverseProperty("KhamBenh")]
        public virtual ICollection<K_BookingDuoc> K_BookingDuoc { get; set; }
        [InverseProperty("KhamBenh")]
        public virtual ICollection<K_ChungTu> K_ChungTu { get; set; }
        [InverseProperty("KhamBenh")]
        public virtual ICollection<K_ToaThuoc> K_ToaThuoc { get; set; }
        [InverseProperty("KhamBenh")]
        public virtual ICollection<K_XacNhanHoanTatKham> K_XacNhanHoanTatKham { get; set; }
        [InverseProperty("KhamBenh")]
        public virtual ICollection<ZaloFile> ZaloFile { get; set; }
    }
}