// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_KTV
    {
        public K_KTV()
        {
            K_CLSKetQua = new HashSet<K_CLSKetQua>();
            K_CLSKetQua_CDHA = new HashSet<K_CLSKetQua_CDHA>();
        }

        [Key]
        public int KTV_Id { get; set; }
        [StringLength(50)]
        public string TenKTV { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("KTVThucHien")]
        public virtual ICollection<K_CLSKetQua> K_CLSKetQua { get; set; }
        [InverseProperty("KTVThucHien")]
        public virtual ICollection<K_CLSKetQua_CDHA> K_CLSKetQua_CDHA { get; set; }
    }
}