// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_LoaiPhongBan
    {
        public K_LoaiPhongBan()
        {
            K_PhongBan = new HashSet<K_PhongBan>();
        }

        [Key]
        public int LoaiPhongBan_Id { get; set; }
        [StringLength(50)]
        public string MaLoaiPhongBan { get; set; }
        [StringLength(250)]
        public string TenLoaiPhongBan { get; set; }
        public int? TamNgung { get; set; }
        public int? Huy { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }

        [InverseProperty("LoaiPhongBan")]
        public virtual ICollection<K_PhongBan> K_PhongBan { get; set; }
    }
}