// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_MapNhomBenhDichVu
    {
        [Key]
        public int MapNhomBenhDichVu_Id { get; set; }
        public int? NhomBenh_Id { get; set; }
        public int? DichVu_Id { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("DichVu_Id")]
        [InverseProperty("K_MapNhomBenhDichVu")]
        public virtual K_DichVu DichVu { get; set; }
        [ForeignKey("NhomBenh_Id")]
        [InverseProperty("K_MapNhomBenhDichVu")]
        public virtual K_NhomBenh NhomBenh { get; set; }
    }
}