// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_MapGoiVacxinMauVoiDuoc
    {
        [Key]
        public int MapGoiVacxinMauVoiDuoc_Id { get; set; }
        public int? GoiVacxinMau_Id { get; set; }
        public int? Duoc_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuong { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_MapGoiVacxinMauVoiDuoc")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("GoiVacxinMau_Id")]
        [InverseProperty("K_MapGoiVacxinMauVoiDuoc")]
        public virtual K_GoiVacxinMau GoiVacxinMau { get; set; }
    }
}