// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Menu
    {
        public K_Menu()
        {
            InverseParentMenuNavigation = new HashSet<K_Menu>();
            K_Permission = new HashSet<K_Permission>();
        }

        [Key]
        public int Menu_Id { get; set; }
        [StringLength(50)]
        public string MenuCode { get; set; }
        [StringLength(250)]
        public string MenuName { get; set; }
        public int? ParentMenu { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("ParentMenu")]
        [InverseProperty("InverseParentMenuNavigation")]
        public virtual K_Menu ParentMenuNavigation { get; set; }
        [InverseProperty("ParentMenuNavigation")]
        public virtual ICollection<K_Menu> InverseParentMenuNavigation { get; set; }
        [InverseProperty("Menu")]
        public virtual ICollection<K_Permission> K_Permission { get; set; }
    }
}