// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_MucDichChungTu
    {
        [Key]
        public int MucDichChungTu_ID { get; set; }
        [StringLength(100)]
        public string MaMucDich { get; set; }
        [StringLength(100)]
        public string TenMucDich { get; set; }
    }
}