// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_NhomBenh
    {
        public K_NhomBenh()
        {
            K_MapNhomBenhDichVu = new HashSet<K_MapNhomBenhDichVu>();
        }

        [Key]
        public int NhomBenh_Id { get; set; }
        [StringLength(150)]
        public string MaNhomBenh { get; set; }
        [StringLength(500)]
        public string TenNhomBenh { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("NhomBenh")]
        public virtual ICollection<K_MapNhomBenhDichVu> K_MapNhomBenhDichVu { get; set; }
    }
}