// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_NhomDichVu
    {
        public K_NhomDichVu()
        {
            K_DichVu = new HashSet<K_DichVu>();
        }

        [Key]
        public int NhomDichVu_Id { get; set; }
        [StringLength(150)]
        public string MaNhomDichVu { get; set; }
        [StringLength(500)]
        public string TenNhomDichVu { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }
        public int? LoaiDichVu_Id { get; set; }

        [InverseProperty("NhomDichVu")]
        public virtual ICollection<K_DichVu> K_DichVu { get; set; }
    }
}