// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_NoiDungMailHinhAnh
    {
        [Key]
        public int NoiDungMailHinhAnh_Id { get; set; }
        public int? NoiDungMail_Id { get; set; }
        [StringLength(250)]
        public string HinhAnhName { get; set; }
        [Column(TypeName = "ntext")]
        public string HinhAnhDuongDan { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("NoiDungMail_Id")]
        [InverseProperty("K_NoiDungMailHinhAnh")]
        public virtual K_NoiDungMail NoiDungMail { get; set; }
    }
}