// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_NoiDungMail
    {
        public K_NoiDungMail()
        {
            K_NoiDungMailHinhAnh = new HashSet<K_NoiDungMailHinhAnh>();
        }

        [Key]
        public int NoiDungMail_Id { get; set; }
        [StringLength(250)]
        public string TieuDe { get; set; }
        [Column(TypeName = "ntext")]
        public string NoiDung { get; set; }
        [Column(TypeName = "ntext")]
        public string NoiDung_text { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayGui { get; set; }
        public int? NguoiGui { get; set; }

        [InverseProperty("NoiDungMail")]
        public virtual ICollection<K_NoiDungMailHinhAnh> K_NoiDungMailHinhAnh { get; set; }
    }
}