// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Permission_DichVu
    {
        [Key]
        public int Permission_DichVu_Id { get; set; }
        public int? PhongBan_Id { get; set; }
        public int? Dich_Id { get; set; }

        [ForeignKey("Dich_Id")]
        [InverseProperty("K_Permission_DichVu")]
        public virtual K_DichVu Dich { get; set; }
        [ForeignKey("PhongBan_Id")]
        [InverseProperty("K_Permission_DichVu")]
        public virtual K_PhongBan PhongBan { get; set; }
    }
}