// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_PhienDangNhap
    {
        public K_PhienDangNhap()
        {
            K_Action = new HashSet<K_Action>();
            K_Action_ChungTu = new HashSet<K_Action_ChungTu>();
            K_BookingDuoc = new HashSet<K_BookingDuoc>();
            K_BookingTiemChung = new HashSet<K_BookingTiemChung>();
            K_DuocTonKhoBooking = new HashSet<K_DuocTonKhoBooking>();
        }

        [Key]
        public int PhienDangNhap_Id { get; set; }
        public int? User_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianDangNhap { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianKetThuc { get; set; }
        [StringLength(50)]
        public string Ip { get; set; }
        [StringLength(150)]
        public string Mac { get; set; }
        public int? PhongBan_Id { get; set; }
        public int? KhoDuoc_Id { get; set; }

        [ForeignKey("KhoDuoc_Id")]
        [InverseProperty("K_PhienDangNhap")]
        public virtual K_KhoDuoc KhoDuoc { get; set; }
        [ForeignKey("PhongBan_Id")]
        [InverseProperty("K_PhienDangNhap")]
        public virtual K_PhongBan PhongBan { get; set; }
        [ForeignKey("User_Id")]
        [InverseProperty("K_PhienDangNhap")]
        public virtual K_Users User { get; set; }
        [InverseProperty("PhienDangNhap")]
        public virtual ICollection<K_Action> K_Action { get; set; }
        [InverseProperty("PhienDangNhap")]
        public virtual ICollection<K_Action_ChungTu> K_Action_ChungTu { get; set; }
        [InverseProperty("PhienDangNhap")]
        public virtual ICollection<K_BookingDuoc> K_BookingDuoc { get; set; }
        [InverseProperty("PhienDangNhap")]
        public virtual ICollection<K_BookingTiemChung> K_BookingTiemChung { get; set; }
        [InverseProperty("PhienDangNhap")]
        public virtual ICollection<K_DuocTonKhoBooking> K_DuocTonKhoBooking { get; set; }
    }
}