// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_PhongBan
    {
        public K_PhongBan()
        {
            DM_BacSi_PhongKham_User = new HashSet<DM_BacSi_PhongKham_User>();
            K_CLSYeuCau = new HashSet<K_CLSYeuCau>();
            K_HoaDon = new HashSet<K_HoaDon>();
            K_Permission_DichVu = new HashSet<K_Permission_DichVu>();
            K_PhienDangNhap = new HashSet<K_PhienDangNhap>();
            K_TiepNhan = new HashSet<K_TiepNhan>();
            K_Users_PhongBan = new HashSet<K_Users_PhongBan>();
        }

        [Key]
        public int PhongBan_Id { get; set; }
        [StringLength(50)]
        public string MaPhongBan { get; set; }
        [StringLength(250)]
        public string TenPhongBan { get; set; }
        public int? LoaiPhongBan_Id { get; set; }
        public int? TamNgung { get; set; }
        public int? Huy { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }

        [ForeignKey("LoaiPhongBan_Id")]
        [InverseProperty("K_PhongBan")]
        public virtual K_LoaiPhongBan LoaiPhongBan { get; set; }
        [InverseProperty("PhongBan")]
        public virtual ICollection<DM_BacSi_PhongKham_User> DM_BacSi_PhongKham_User { get; set; }
        [InverseProperty("NoiThucHien")]
        public virtual ICollection<K_CLSYeuCau> K_CLSYeuCau { get; set; }
        [InverseProperty("NoiPhatSinh")]
        public virtual ICollection<K_HoaDon> K_HoaDon { get; set; }
        [InverseProperty("PhongBan")]
        public virtual ICollection<K_Permission_DichVu> K_Permission_DichVu { get; set; }
        [InverseProperty("PhongBan")]
        public virtual ICollection<K_PhienDangNhap> K_PhienDangNhap { get; set; }
        [InverseProperty("NoiTiepNhan")]
        public virtual ICollection<K_TiepNhan> K_TiepNhan { get; set; }
        [InverseProperty("PhongBan")]
        public virtual ICollection<K_Users_PhongBan> K_Users_PhongBan { get; set; }
    }
}