// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Setting
    {
        [Key]
        public int Setting_Id { get; set; }
        [StringLength(250)]
        public string SettingCode { get; set; }
        [StringLength(500)]
        public string SettingName { get; set; }
        public string NoiDung { get; set; }
        [Column(TypeName = "ntext")]
        public string Mota { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date1 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date2 { get; set; }
        public int? Num1 { get; set; }
        public int? Num2 { get; set; }
        [StringLength(250)]
        public string String1 { get; set; }
        [StringLength(250)]
        public string String2 { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }
    }
}