// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_SoTiemChung
    {
        public K_SoTiemChung()
        {
            K_BookingTiemChung = new HashSet<K_BookingTiemChung>();
            K_TiemChung = new HashSet<K_TiemChung>();
        }

        [Key]
        public int SoTiemChung_Id { get; set; }
        [StringLength(50)]
        public string MaSoTiemChung { get; set; }
        public int? BenhNhan_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }

        [ForeignKey("BenhNhan_Id")]
        [InverseProperty("K_SoTiemChung")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [InverseProperty("SoTiemChung")]
        public virtual ICollection<K_BookingTiemChung> K_BookingTiemChung { get; set; }
        [InverseProperty("SoTiemChung")]
        public virtual ICollection<K_TiemChung> K_TiemChung { get; set; }
    }
}