// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_TiepNhan
    {
        public K_TiepNhan()
        {
            K_BookingTiemChung = new HashSet<K_BookingTiemChung>();
            K_CLSKetQua = new HashSet<K_CLSKetQua>();
            K_CLSKetQua_CDHA = new HashSet<K_CLSKetQua_CDHA>();
            K_CLSYeuCau = new HashSet<K_CLSYeuCau>();
            K_HoaDon = new HashSet<K_HoaDon>();
            K_KhamBenh = new HashSet<K_KhamBenh>();
            K_KhamSangLoc = new HashSet<K_KhamSangLoc>();
            K_ThongTinDai = new HashSet<K_ThongTinDai>();
            K_TiemChung = new HashSet<K_TiemChung>();
            K_XacNhanHoanTatKham = new HashSet<K_XacNhanHoanTatKham>();
            XetNghiemFile = new HashSet<XetNghiemFile>();
        }

        [Key]
        public int TiepNhan_Id { get; set; }
        [StringLength(50)]
        public string SoTiepNhan { get; set; }
        public int? SoThuTu { get; set; }
        public int? UuTien { get; set; }
        public int? BenhNhan_Id { get; set; }
        public int? NoiTiepNhan_Id { get; set; }
        public int? NguoiTiepNhan_Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTiepNhan { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ThoiGianTiepNhan { get; set; }
        public int? NamTiepNhan { get; set; }
        public int? ThangTiepNhan { get; set; }
        [StringLength(500)]
        public string DiaChiLienHe { get; set; }
        [StringLength(500)]
        public string GhiChu { get; set; }
        public int? BacSiChiDinh { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }
        [StringLength(500)]
        public string LyDoKham { get; set; }
        public int? LoaiTiemChung { get; set; }
        public int? CoThai { get; set; }
        [Column(TypeName = "date")]
        public DateTime? NgayTiem { get; set; }
        [Column(TypeName = "date")]
        public DateTime? NgayNhacMuiTiepTheo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ThoiGianTiem { get; set; }

        [ForeignKey("BenhNhan_Id")]
        [InverseProperty("K_TiepNhan")]
        public virtual K_BenhNhan BenhNhan { get; set; }
        [ForeignKey("NoiTiepNhan_Id")]
        [InverseProperty("K_TiepNhan")]
        public virtual K_PhongBan NoiTiepNhan { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_BookingTiemChung> K_BookingTiemChung { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_CLSKetQua> K_CLSKetQua { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_CLSKetQua_CDHA> K_CLSKetQua_CDHA { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_CLSYeuCau> K_CLSYeuCau { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_HoaDon> K_HoaDon { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_KhamBenh> K_KhamBenh { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_KhamSangLoc> K_KhamSangLoc { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_ThongTinDai> K_ThongTinDai { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_TiemChung> K_TiemChung { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<K_XacNhanHoanTatKham> K_XacNhanHoanTatKham { get; set; }
        [InverseProperty("TiepNhan")]
        public virtual ICollection<XetNghiemFile> XetNghiemFile { get; set; }
    }
}