// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_TiemChung
    {
        public K_TiemChung()
        {
            K_BookingTiemChung = new HashSet<K_BookingTiemChung>();
            K_HoaDonChiTiet = new HashSet<K_HoaDonChiTiet>();
        }

        [Key]
        public int TiemChung_Id { get; set; }
        public int? TiepNhan_Id { get; set; }
        [StringLength(50)]
        public string SoThuTuToa { get; set; }
        public int? Duoc_Id { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? SoLuong { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? DonGia { get; set; }
        [Column(TypeName = "numeric")]
        [DecimalPrecision(18,2)]
        public decimal? ThanhTien { get; set; }
        public int? DaCho { get; set; }
        public int? SoLuongDaCho { get; set; }
        public int? DaThanhToan { get; set; }
        public int? MuiTiem_Id { get; set; }
        public int? TiepNhan_IdDaTiem { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTiem { get; set; }
        [StringLength(10)]
        public string XacNhanTiem { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayHenTiem { get; set; }
        public int? NguoiTao { get; set; }
        [StringLength(500)]
        public string GhiChu { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }
        public int? SoTiemChung_Id { get; set; }
        [StringLength(10)]
        public string XacNhanThu { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayThu { get; set; }
        [StringLength(15)]
        public string XacNhanDaTheoDoi { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayPhanUng { get; set; }
        public int? PhanUngPhuTaiChoId { get; set; }
        public int? PhanUngPhuToanThanId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayHenSMS { get; set; }
        [StringLength(15)]
        public string ChuyenKhoKhach { get; set; }
        public int? SoLoNhap_Id { get; set; }
        public int? DuocTonKho_Id { get; set; }
        [StringLength(15)]
        public string DaXuat { get; set; }
        public int? ChungTuChiTiet_IdXNB { get; set; }
        public int? ChungTuChiTiet_IdNNB { get; set; }
        public int? ChungTuChiTiet_IdXSD { get; set; }
        public int? LaVacXinNhaThuoc { get; set; }

        [ForeignKey("Duoc_Id")]
        [InverseProperty("K_TiemChung")]
        public virtual K_DM_Duoc Duoc { get; set; }
        [ForeignKey("DuocTonKho_Id")]
        [InverseProperty("K_TiemChung")]
        public virtual K_DuocTonKho DuocTonKho { get; set; }
        [ForeignKey("MuiTiem_Id")]
        [InverseProperty("K_TiemChungMuiTiem")]
        public virtual K_Dictionary MuiTiem { get; set; }
        [ForeignKey("PhanUngPhuTaiChoId")]
        [InverseProperty("K_TiemChungPhanUngPhuTaiCho")]
        public virtual K_Dictionary PhanUngPhuTaiCho { get; set; }
        [ForeignKey("PhanUngPhuToanThanId")]
        [InverseProperty("K_TiemChungPhanUngPhuToanThan")]
        public virtual K_Dictionary PhanUngPhuToanThan { get; set; }
        [ForeignKey("SoLoNhap_Id")]
        [InverseProperty("K_TiemChung")]
        public virtual K_ChungTuSoLoNhap SoLoNhap { get; set; }
        [ForeignKey("SoTiemChung_Id")]
        [InverseProperty("K_TiemChung")]
        public virtual K_SoTiemChung SoTiemChung { get; set; }
        [ForeignKey("TiepNhan_Id")]
        [InverseProperty("K_TiemChung")]
        public virtual K_TiepNhan TiepNhan { get; set; }
        [InverseProperty("TiemChung")]
        public virtual ICollection<K_BookingTiemChung> K_BookingTiemChung { get; set; }
        [InverseProperty("TiemChung")]
        public virtual ICollection<K_HoaDonChiTiet> K_HoaDonChiTiet { get; set; }
    }
}