// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_ToaThuocMau
    {
        public K_ToaThuocMau()
        {
            K_MapToaThuocMauVoiDuoc = new HashSet<K_MapToaThuocMauVoiDuoc>();
        }

        [Key]
        public int ToaThuocMau_Id { get; set; }
        [StringLength(150)]
        public string MaToaThuocMau { get; set; }
        [StringLength(500)]
        public string TenToaThuocMau { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("ToaThuocMau")]
        public virtual ICollection<K_MapToaThuocMauVoiDuoc> K_MapToaThuocMauVoiDuoc { get; set; }
    }
}