// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_TuDienKetLuan
    {
        [Key]
        public int TuDienKetLuan_Id { get; set; }
        [StringLength(50)]
        public string MaTuDien { get; set; }
        [StringLength(250)]
        public string TenTuDien { get; set; }
        [StringLength(50)]
        public string STT { get; set; }
        [StringLength(500)]
        public string TieuDe { get; set; }
        public int? GioiTinh { get; set; }
        [StringLength(500)]
        public string ChanDoan { get; set; }
        public int? TinhNgayDuSinh { get; set; }
        [Column(TypeName = "ntext")]
        public string KetLuan { get; set; }
        [Column(TypeName = "ntext")]
        public string MoTa { get; set; }
        [Column(TypeName = "ntext")]
        public string Mota_text { get; set; }
        [Column(TypeName = "ntext")]
        public string GhiChu { get; set; }
        [Column(TypeName = "ntext")]
        public string LoiDan { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }
        public int? DichVu_Id { get; set; }

        [ForeignKey("DichVu_Id")]
        [InverseProperty("K_TuDienKetLuan")]
        public virtual K_DichVu DichVu { get; set; }
    }
}