// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_TuDienChanDoanKhamBenh
    {
        [Key]
        public int TuDienChanDoan_Id { get; set; }
        [StringLength(50)]
        public string MaTuDien { get; set; }
        [StringLength(250)]
        public string TenTuDien { get; set; }
        [StringLength(50)]
        public string STT { get; set; }
        [StringLength(500)]
        public string TieuDe { get; set; }
        public string ChanDoan { get; set; }
        public int? TinhNgayDuSinh { get; set; }
        [Column(TypeName = "ntext")]
        public string LoiDan { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }
    }
}