// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Users_PhongBan
    {
        [Key]
        public int User_PhongBan_Id { get; set; }
        public int? User_Id { get; set; }
        public int? PhongBan_Id { get; set; }

        [ForeignKey("PhongBan_Id")]
        [InverseProperty("K_Users_PhongBan")]
        public virtual K_PhongBan PhongBan { get; set; }
        [ForeignKey("User_Id")]
        [InverseProperty("K_Users_PhongBan")]
        public virtual K_Users User { get; set; }
    }
}