// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Users_KhoDuoc
    {
        [Key]
        public int User_PhongBan_Id { get; set; }
        public int? User_Id { get; set; }
        public int? KhoDuoc_Id { get; set; }

        [ForeignKey("KhoDuoc_Id")]
        public virtual K_KhoDuoc KhoDuoc { get; set; }
        [ForeignKey("User_Id")]
        public virtual K_Users User { get; set; }
    }
}