// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class K_Users
    {
        public K_Users()
        {
            DM_BacSi_PhongKham_User = new HashSet<DM_BacSi_PhongKham_User>();
            K_Permission = new HashSet<K_Permission>();
            K_Permission_Report = new HashSet<K_Permission_Report>();
            K_PhienDangNhap = new HashSet<K_PhienDangNhap>();
            K_Users_PhongBan = new HashSet<K_Users_PhongBan>();
        }

        [Key]
        public int User_Id { get; set; }
        [StringLength(50)]
        public string UserCode { get; set; }
        [StringLength(250)]
        public string UserName { get; set; }
        [StringLength(500)]
        public string Password { get; set; }
        public int? BenhVien_Id { get; set; }
        public int? TamNgung { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiCapNhat { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? Huy { get; set; }

        [ForeignKey("BenhVien_Id")]
        [InverseProperty("K_Users")]
        public virtual K_BenhVien BenhVien { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<DM_BacSi_PhongKham_User> DM_BacSi_PhongKham_User { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<K_Permission> K_Permission { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<K_Permission_Report> K_Permission_Report { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<K_PhienDangNhap> K_PhienDangNhap { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<K_Users_PhongBan> K_Users_PhongBan { get; set; }
    }
}