// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    [Table("procedureBaoCao")]
    public partial class ProcedureBaoCao
    {
        public ProcedureBaoCao()
        {
            K_Permission_Report = new HashSet<K_Permission_Report>();
            ProcedureParameter = new HashSet<ProcedureParameter>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string MaBaoCao { get; set; }
        [StringLength(100)]
        public string TenBaoCao { get; set; }
        [StringLength(500)]
        public string procedureName { get; set; }
        [StringLength(500)]
        public string ReportFile { get; set; }
        [StringLength(500)]
        public string ExcelTemplateName { get; set; }
        public int? TamNgung { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayCapNhat { get; set; }
        public int? NguoiCapNhat { get; set; }
        public int? Huy { get; set; }

        [InverseProperty("Report")]
        public virtual ICollection<K_Permission_Report> K_Permission_Report { get; set; }
        [InverseProperty("procedureBaoCao")]
        public virtual ICollection<ProcedureParameter> ProcedureParameter { get; set; }
    }
}