// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    [Table("procedureParameter")]
    public partial class ProcedureParameter
    {
        public ProcedureParameter()
        {
            ItemSelect = new HashSet<ItemSelect>();
        }

        [Key]
        public int Id { get; set; }
        public int? NumericalOrder { get; set; }
        public int? typeOfItemSelect { get; set; }
        [StringLength(100)]
        public string ParameterName { get; set; }
        [StringLength(100)]
        public string NameShowLabel { get; set; }
        public int? ValueIntCheckBoxTrue { get; set; }
        public int? ValueIntCheckBoxFalse { get; set; }
        [StringLength(100)]
        public string ValueStringCheckBoxTrue { get; set; }
        [StringLength(100)]
        public string ValueStringCheckBoxFalse { get; set; }
        public int? TypeOfLoadItem { get; set; }
        public int procedureBaoCaoId { get; set; }
        public int TypeOfControlInputId { get; set; }

        [ForeignKey("TypeOfControlInputId")]
        [InverseProperty("procedureParameter")]
        public virtual TypeOfControlInput TypeOfControlInput { get; set; }
        [ForeignKey("procedureBaoCaoId")]
        [InverseProperty("procedureParameter")]
        public virtual ProcedureBaoCao procedureBaoCao { get; set; }
        [InverseProperty("procedureParameter")]
        public virtual ICollection<ItemSelect> ItemSelect { get; set; }
    }
}