// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    [Table("typeOfControlInput")]
    public partial class TypeOfControlInput
    {
        public TypeOfControlInput()
        {
            ProcedureParameter = new HashSet<ProcedureParameter>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string ControlInputName { get; set; }

        [InverseProperty("TypeOfControlInput")]
        public virtual ICollection<ProcedureParameter> ProcedureParameter { get; set; }
    }
}