// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace KClinic2._1.Desktop
{
    public partial class ZaloFile
    {
        [Key]
        public int ZaloFile_Id { get; set; }
        public string DuongDan { get; set; }
        [Column(TypeName = "ntext")]
        public string TokenFile { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NgayTao { get; set; }
        public int? NguoiTao { get; set; }
        public int? CLSKetQua_Id { get; set; }
        public int? CLSKetQuaCDHA_Id { get; set; }
        public int? KhamBenh_Id { get; set; }
        public int? XetNghiemFile_Id { get; set; }
        public int? HoaDon_Id { get; set; }
        public int? PhieuKham_Id { get; set; }

        [ForeignKey("CLSKetQua_Id")]
        [InverseProperty("ZaloFile")]
        public virtual K_CLSKetQua CLSKetQua { get; set; }
        [ForeignKey("CLSKetQuaCDHA_Id")]
        [InverseProperty("ZaloFile")]
        public virtual K_CLSKetQua_CDHA CLSKetQuaCDHA { get; set; }
        [ForeignKey("HoaDon_Id")]
        [InverseProperty("ZaloFile")]
        public virtual K_HoaDon HoaDon { get; set; }
        [ForeignKey("KhamBenh_Id")]
        [InverseProperty("ZaloFile")]
        public virtual K_KhamBenh KhamBenh { get; set; }
        [ForeignKey("XetNghiemFile_Id")]
        [InverseProperty("ZaloFile")]
        public virtual XetNghiemFile XetNghiemFile { get; set; }
    }
}